\input texinfo @c -*-texinfo-*- 

@comment makeinfo --css-include=Lll.css --html Lll.texi
@comment texi2html --css-include=Lll.css Lll.texi
@comment file:///opt/local/share/texinfo/html/texi2html.html

@setfilename Lll.info
@settitle qfwfq, an overview
@afourpaper 

@node Top
@top Tutte le cosmicomiche 

Tutte le cosmicomiche 
@menu
* Introduction:: Introduction
@end menu

LE COSMICOMICHE (cosmicomics) 
@menu
* The Distance of the Moon:: The Distance of the Moon
* At Daybreak:: At Daybreak
* A Sign in Space :: A Sign in Space
* All at One Point:: All at One Point
* Without Colours:: Without Colours
* Games Without End:: Games Without End
* The Aquatic Uncle:: The Aquatic Uncle
* How Much Shall We Bet?:: How Much Shall We Bet?
* The Dinosaurs::  The Dinosaurs
* The Form of Space:: The Form of Space
* The Lightyears:: The Lightyears
* The Spiral:: The Spiral
@end menu

TI CON ZERO (Time and the Hunter)

Part one - more of qfwfq
@menu
* The Soft Moon:: The Soft Moon
* The Origin of the Birds:: The Origin of the Birds
* Crystals:: Crystals
* Blood Sea:: Blood, Sea
@end menu
Part two - Priscilla
@menu
* Mitosis:: Mitosis
* Meiosis:: Meiosis
* Death:: Death
@end menu
Part three - t zero
@menu
* t zero:: t zero
* The Chase:: The Chase
* The Night Driver:: The Night Driver
* The Count of Monte Cristo:: The Count of Monte Cristo
@end menu

ALTRE STORIE COSMICOMICHE
@menu
* La Luna come un fungo:: La Luna come un fungo
* Le figlie della Luna:: Le figlie della Luna
* I meteoriti:: I meteoriti
* Il cielo di pietra:: Il cielo di pietra
* Fino a che dura il Sole:: Fino a che dura il Sole
* Tempesta solare:: Tempesta solare
* Le conchiglie e il tempo:: Le conchiglie e il tempo
* La memoria del mondo:: La memoria del mondo
@end menu

COSMICOMICHE NUOVE
@menu
* Il niente e il poco:: Il niente e il poco
* L'implosione:: L'implosione
@end menu

UNA COSMICOMICA TRANSFORMATA
@menu
* L'altra Euridice:: L'altra Euridice
@end menu

NOTES
@menu
* Bibliography:: Bibliography
@end menu


@node Introduction
@chapter Introduction

``...the ubiquitous Qfwfq, is emblematic of unity amidst the heteroglossic variety
of possibilities offered by expanded degrees of perception made possible by
scientific devices. In one story, Qfwfq is a dinosaur, but in other stories he
is also a fish, a small mammal, a subatomic particle eternally plummeting
through the void. Qfwfq's constantly shifting position in the universe, despite
his consistent first-person narration, suggests the extent to which his form
accommodates his point of view.'' -- Dean Swinford 



@node The Distance of the Moon
@chapter The Distance of the Moon

@node At Daybreak
@chapter At Daybreak

@node A Sign in Space
@chapter A Sign in Space

names and naming, sratching temporary references to the shifting, until
the space itself could not exist independent of the signs forming it.

taming the unnamed. drawing the nameless, sprawling into the realm of
description through imposition of signs, names and references. 

bindings and scope.

@node All at One Point
@chapter All at One Point

@node Without Colours
@chapter Without Colours

establishing similarity and difference. ``sand. not-sand'',
``you-not-I'', ``you-like-I, but only so much''. same, similar, and
substantially indistinguisable. eq?, eqv? and boolean operators.

@node Games Without End
@chapter Games Without End

recursion, and mutual engagement, creating the space as we go... .

@node The Aquatic Uncle
@chapter The Aquatic Uncle

``In 'The Aquatic Uncle,' which precedes the story of the last dinosaur,
Qfwfq, here featured as some sort of protoamphibian, venerates the
reptilian and eschews his ichthyoid 'roots. In Cosmicomics, Qfwfq
encompasses all points of view except for non-existence. As a result,
his various incarnations cannot be contrasted: they are all linked to
one another. While Qfwfq venerates the reptilian and consciously
attempts to conceal his water-bound past, in 'The Dinosaurs,' none of
the mammals recognize that Qfwfq, a dinosaur, is actually a dinosaur.''
--Dean Swinford

learning to swim, amongst creatures who are too proud of their
legs. history and superstition, parallel worlds and ffi. 

@node How Much Shall We Bet?
@chapter How Much Shall We Bet?

probability, chance and ambivalence. the 'random' and 'amb' opertors

@node The Dinosaurs
@chapter The Dinosaurs

@node The Form of Space
@chapter The Form of Space

@node The Lightyears
@chapter The Lightyears

@node The Spiral
@chapter The Spiral

@lisp
(require (lib "40.ss" "srfi"))
 
(define (fibgen a b)
  (stream-cons a (fibgen b (+ a b))))

(define fibonacci (fibgen 0 1))
@end lisp

@comment TI CON ZERO (Time and the Hunter)

@comment Part one - more of qfwfq
@node The Soft Moon
@chapter The Soft Moon

@node The Origin of the Birds
@chapter The Origin of the Birds

@node Crystals
@chapter Crystals

@node Blood Sea
@chapter Blood, Sea

@comment Part two - Priscilla

@node Mitosis
@chapter Mitosis

@node Meiosis
@chapter Meiosis

@node Death
@chapter Death

@comment Part three - t zero

@node t zero
@chapter t zero

@node The Chase
@chapter The Chase

@node The Night Driver
@chapter The Night Driver

@node The Count of Monte Cristo
@chapter The Count of Monte Cristo

@comment ALTRE STORIE COSMICOMICHE

@node La Luna come un fungo
@chapter La Luna come un fungo

@node Le figlie della Luna
@chapter Le figlie della Luna

@node I meteoriti
@chapter I meteoriti

@node Il cielo di pietra
@chapter Il cielo di pietra

@node Fino a che dura il Sole
@chapter Fino a che dura il Sole

@node Tempesta solare
@chapter Tempesta solare

@node Le conchiglie e il tempo
@chapter Le conchiglie e il tempo

@node La memoria del mondo
@chapter La memoria del mondo

@comment COSMICOMICHE NUOVE

@node Il niente e il poco
@chapter Il niente e il poco

@node L'implosione
@chapter L'implosione

@node L'altra Euridice
@chapter L'altra Euridice

@lisp
(eval 'apply)
@end lisp


@node Bibliography
@chapter Bibliography

@enumerate
@item 'Tutte le cosmicomiche' edizione Mondadori 1997 - isbn 88-04-52046-9
@item 'Cosmicomics' picador edition 1993. translated by william weaver - isbn 0 330 31908 6
@item 'Time and the Hunter' picador edition 1993. translated by william weaver - isbn 0 330 31909 4
@item 'Defining irrealism: scientific development and allegorical possibility' by Dean Swinford 
@end enumerate


@bye 
